In [1]:
import tensorflow as tf

In [2]:
tf.set_random_seed(777)

In [3]:
x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]


# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

In [4]:
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

In [5]:
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-10).minimize(cost)

In [6]:
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [7]:
# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(201):
        cost_val, W_val, _ = sess.run(
            [cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)

    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 5.73203 [[ 0.80269563  0.67861295 -1.2172831 ]
 [-0.3051686  -0.3032113   1.508257  ]
 [ 0.7572236  -0.7008909  -2.108204  ]]
1 5.73203 [[ 0.80269563  0.67861295 -1.2172831 ]
 [-0.3051686  -0.3032113   1.508257  ]
 [ 0.7572236  -0.7008909  -2.108204  ]]
2 5.73203 [[ 0.80269563  0.67861295 -1.2172831 ]
 [-0.3051686  -0.3032113   1.508257  ]
 [ 0.7572236  -0.7008909  -2.108204  ]]
3 5.73203 [[ 0.80269563  0.67861295 -1.2172831 ]
 [-0.3051686  -0.3032113   1.508257  ]
 [ 0.7572236  -0.7008909  -2.108204  ]]
4 5.73203 [[ 0.80269563  0.67861295 -1.2172831 ]
 [-0.3051686  -0.3032113   1.508257  ]
 [ 0.7572236  -0.7008909  -2.108204  ]]
5 5.73203 [[ 0.80269563  0.67861295 -1.2172831 ]
 [-0.3051686  -0.3032113   1.508257  ]
 [ 0.7572236  -0.7008909  -2.108204  ]]
6 5.73203 [[ 0.80269563  0.67861295 -1.2172831 ]
 [-0.3051686  -0.3032113   1.508257  ]
 [ 0.7572236  -0.7008909  -2.108204  ]]
7 5.73203 [[ 0.80269563  0.67861295 -1.2172831 ]
 [-0.3051686  -0.3032113   1.508257  ]
 [ 0.7572236  -0

In [8]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1.5).minimize(cost)

In [11]:
# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(201):
        cost_val, W_val, _ = sess.run(
            [cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        if (step % 20 == 0):
            print(step, cost_val, W_val)

    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 5.73203 [[-0.30548954  1.2298503  -0.66033536]
 [-4.3907      2.2967086   2.9938684 ]
 [-3.345107    2.0974321  -0.80419564]]
20 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
40 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
60 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
80 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
100 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
120 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
140 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
160 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
180 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
200 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
Prediction: [0 0 0]
Accuracy:  0.0


In [12]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [13]:
# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(201):
        cost_val, W_val, _ = sess.run(
            [cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        if (step % 20 == 0):
            print(step, cost_val, W_val)

    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 5.73203 [[ 0.7288166   0.7153621  -1.1801533 ]
 [-0.57753736 -0.12988332  1.6072978 ]
 [ 0.48373488 -0.51433605 -2.02127   ]]
20 1.6610024 [[ 0.35837555  0.7006911  -0.79504126]
 [-0.5218104  -0.14752226  1.5692096 ]
 [-0.00524238 -0.21694626 -1.8296826 ]]
40 1.4070582 [[ 0.08632906  0.6441534  -0.4664571 ]
 [-0.27831453 -0.19541714  1.3736086 ]
 [-0.14105876 -0.16434807 -1.7464645 ]]
60 1.2188071 [[-0.14574495  0.580433   -0.17066269]
 [-0.1107576  -0.17286882  1.1835034 ]
 [-0.2245029  -0.17601469 -1.6513535 ]]
80 1.0710086 [[-0.3455095   0.5168773   0.09265763]
 [ 0.01382132 -0.11677328  1.0028291 ]
 [-0.28096494 -0.21812555 -1.5527805 ]]
100 0.9537603 [[-0.52009284  0.45806164  0.32605675]
 [ 0.11236367 -0.04872466  0.836238  ]
 [-0.3214388  -0.27116382 -1.4592681 ]]
120 0.86215675 [[-0.67484623  0.40643024  0.5324416 ]
 [ 0.19237746  0.01887316  0.68862635]
 [-0.3494764  -0.32348    -1.3789142 ]]
140 0.7924157 [[-0.81354636  0.36310616  0.714466  ]
 [ 0.25704384  0.07866935  0.5

In [14]:
import numpy as np

In [15]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

In [16]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [19]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [20]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b
xz
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [22]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if (step % 20 == 0):
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  2019921800000.0 
Prediction:
 [[1003463.9]
 [2018910.5]
 [1588441.4]
 [1113822. ]
 [1312501. ]
 [1323536.8]
 [1213151.5]
 [1544276.8]]
20 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
40 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
60 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
80 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
100 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]


In [23]:
xy

array([[8.28659973e+02, 8.33450012e+02, 9.08100000e+05, 8.28349976e+02,
        8.31659973e+02],
       [8.23020020e+02, 8.28070007e+02, 1.82810000e+06, 8.21655029e+02,
        8.28070007e+02],
       [8.19929993e+02, 8.24400024e+02, 1.43810000e+06, 8.18979980e+02,
        8.24159973e+02],
       [8.16000000e+02, 8.20958984e+02, 1.00810000e+06, 8.15489990e+02,
        8.19239990e+02],
       [8.19359985e+02, 8.23000000e+02, 1.18810000e+06, 8.18469971e+02,
        8.18979980e+02],
       [8.19000000e+02, 8.23000000e+02, 1.19810000e+06, 8.16000000e+02,
        8.20450012e+02],
       [8.11700012e+02, 8.15250000e+02, 1.09810000e+06, 8.09780029e+02,
        8.13669983e+02],
       [8.09510010e+02, 8.16659973e+02, 1.39810000e+06, 8.04539978e+02,
        8.09559998e+02]])

In [24]:
def MinMaxScaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

In [25]:
xy = MinMaxScaler(xy)

In [26]:
xy

array([[0.99999999, 0.99999999, 0.        , 1.        , 1.        ],
       [0.70548491, 0.70439552, 1.        , 0.71881782, 0.83755791],
       [0.54412549, 0.50274824, 0.57608696, 0.606468  , 0.6606331 ],
       [0.33890353, 0.31368023, 0.10869565, 0.45989134, 0.43800918],
       [0.51436   , 0.42582389, 0.30434783, 0.58504805, 0.42624401],
       [0.49556179, 0.42582389, 0.31521739, 0.48131134, 0.49276137],
       [0.11436064, 0.        , 0.20652174, 0.22007776, 0.18597238],
       [0.        , 0.07747099, 0.5326087 , 0.        , 0.        ]])

In [28]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [29]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if (step % 20 == 0):
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  0.10567288 
Prediction:
 [[ 0.8542941 ]
 [ 1.562238  ]
 [ 0.86688405]
 [ 0.13131964]
 [ 0.48175365]
 [ 0.42280787]
 [-0.17695826]
 [ 0.150666  ]]
20 Cost:  0.10565975 
Prediction:
 [[ 0.85423154]
 [ 1.5621493 ]
 [ 0.86682063]
 [ 0.13128406]
 [ 0.48170334]
 [ 0.422759  ]
 [-0.17698473]
 [ 0.15062982]]
40 Cost:  0.10564661 
Prediction:
 [[ 0.85416895]
 [ 1.5620606 ]
 [ 0.866757  ]
 [ 0.13124853]
 [ 0.48165315]
 [ 0.42271012]
 [-0.17701119]
 [ 0.15059364]]
60 Cost:  0.10563348 
Prediction:
 [[ 0.85410637]
 [ 1.5619719 ]
 [ 0.8666937 ]
 [ 0.13121307]
 [ 0.48160297]
 [ 0.42266124]
 [-0.17703766]
 [ 0.15055746]]
80 Cost:  0.10562041 
Prediction:
 [[ 0.8540442 ]
 [ 1.5618837 ]
 [ 0.86663055]
 [ 0.1311779 ]
 [ 0.4815532 ]
 [ 0.4226128 ]
 [-0.17706373]
 [ 0.1505217 ]]
100 Cost:  0.10560733 
Prediction:
 [[ 0.8539828 ]
 [ 1.561796  ]
 [ 0.8665683 ]
 [ 0.13114357]
 [ 0.48150408]
 [ 0.4225651 ]
 [-0.17708904]
 [ 0.15048671]]


In [30]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)
train = optimizer.minimize(cost)

In [31]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if (step % 20 == 0):
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  0.10567288 
Prediction:
 [[ 0.8542941 ]
 [ 1.562238  ]
 [ 0.86688405]
 [ 0.13131964]
 [ 0.48175365]
 [ 0.42280787]
 [-0.17695826]
 [ 0.150666  ]]
20 Cost:  0.057819232 
Prediction:
 [[ 0.83765113]
 [ 1.3057548 ]
 [ 0.74582505]
 [ 0.1585238 ]
 [ 0.44098973]
 [ 0.38048768]
 [-0.14570546]
 [ 0.09373164]]
40 Cost:  0.033911753 
Prediction:
 [[ 0.88954353]
 [ 1.1817288 ]
 [ 0.7119745 ]
 [ 0.22298026]
 [ 0.46213222]
 [ 0.39893907]
 [-0.08579984]
 [ 0.08840626]]
60 Cost:  0.020581514 
Prediction:
 [[ 0.9257903 ]
 [ 1.0892644 ]
 [ 0.68696475]
 [ 0.27144912]
 [ 0.4780322 ]
 [ 0.41287276]
 [-0.0394471 ]
 [ 0.08645877]]
80 Cost:  0.013135838 
Prediction:
 [[ 0.95152843]
 [ 1.0202949 ]
 [ 0.6684524 ]
 [ 0.30783197]
 [ 0.49000922]
 [ 0.42334393]
 [-0.00394234]
 [ 0.08593473]]
100 Cost:  0.008970037 
Prediction:
 [[0.97002053]
 [0.968838  ]
 [0.6547408 ]
 [0.33511448]
 [0.4990536 ]
 [0.43118578]
 [0.02308993]
 [0.08591594]]


In [32]:
x_data

array([[0.99999999, 0.99999999, 0.        , 1.        ],
       [0.70548491, 0.70439552, 1.        , 0.71881782],
       [0.54412549, 0.50274824, 0.57608696, 0.606468  ],
       [0.33890353, 0.31368023, 0.10869565, 0.45989134],
       [0.51436   , 0.42582389, 0.30434783, 0.58504805],
       [0.49556179, 0.42582389, 0.31521739, 0.48131134],
       [0.11436064, 0.        , 0.20652174, 0.22007776],
       [0.        , 0.07747099, 0.5326087 , 0.        ]])

In [33]:
y_data

array([[1.        ],
       [0.83755791],
       [0.6606331 ],
       [0.43800918],
       [0.42624401],
       [0.49276137],
       [0.18597238],
       [0.        ]])